### ISSUE TITLE
Lazy load component with arguments

### ISSUE THREAD

**Issue by konrad-ch** [thheller/code-splitting-clojurescript#1]
Hello, how can I lazy load component which has some arguments? An example would be great!

**Comment by thheller** [comment]
Not sure I understand the question?

The example has
```
        :product-detail
        [:> product-detail {}]

        :sign-in
        [:> sign-in {}]
```

`{}` is the arguments? just pass whatever you want there?

so
```
        :sign-in
        [:> sign-in {:x "foo"}]
```
and
```
(ns demo.components.sign-in
  (:require [demo.env :as env]))

(defn root [{:keys [x]}]
  [:div
   [:h1 "Sign In: " x] ;; x is "foo"
   [:p "imagine a form ..."]
   [:button {:on-click #(swap! env/app-state assoc :signed-in true :page :account-overview)} "Sign me in already!"]])
```

**Comment by konrad-ch** [comment]
Yes, I've tried that but failed. The ```x``` is ```nil``` :(
I have used exactly the same code as you described above.

**Comment by thheller** [comment]
Oh right. You need to change the dummy `demo/util.cljs` to include props.
```
(defn lazy-component* [loadable]
  (react/lazy
    (fn []
      (-> (lazy/load loadable)
          (.then (fn [root-el]
                   ;; React.lazy expects to load a ES6 module with a React Component as default export

                   ;; this would be more correct in production settings
                   ;; #js {:default (r/reactify-component root-el)}

                   ;; we need wrap the loaded component one extra level so live-reload actually works
                   ;; since React will keep a reference to the initially loaded fn and won't update it
                   #js {:default (r/reactify-component (fn [props] [@loadable props]))}
                   ))))))

```

**Comment by thheller** [comment]
Updated the example to include that fix.

**Comment by konrad-ch** [comment]
Thank you!

**Comment by konrad-ch** [comment]
Ok, one more thing I have to ask - why is the argument value omitted if it has a dash in key name? Example:
```:sign-in
        [:> sign-in {:x-y "foo"}]

**Comment by thheller** [comment]
Good question. I guess due to the `:>` reagent is converting the params to a JS object and probably converts to camelCase or so. I'm not too familiar with those aspects of reagent so I'm not sure how to deal with that exactly.

Maybe someone more knowledgable with reagent knows to properly do this?

**Comment by fricze** [comment]
The easiest thing to do here is to avoid using React Suspense and React lazy at all. Reagent atom that keeps loadable component is simpler and avoids all this "translate reagent component to react then back to reagent again".

**Comment by fricze** [comment]
I know issue is old but I was fighting this today, so https://github.com/jonki/code-splitting-clojurescript
A little different API but works
